
---
# tasks file for service-install-run
- name: create main directories
  file:
    dest: /ahmed/etc/
    mode: 0775
    recurse: yes
    state: directory

- name: insert config file
  template:
    src: application.properties.j2
    dest: /ahmed/etc/application.properties
    mode: 0755

- name: insert docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /ahmed/etc/docker-compose.yml
    mode: 0755

- name: login to registry
  shell: "docker login {{ registry_url }} -u {{ registry_user }} -p {{ registry_password }}"

- name: run docker-compose
  shell: docker-compose -f /ahmed/etc/docker-compose.yml down

- name: run docker-compose
  shell: docker-compose -f /ahmed/etc/docker-compose.yml up 

- name: wait for instance
  uri:
    url: "http://127.0.0.1:8080/api/EduHousing/v1.0.0/college/findAll"
    status_code: 404
  register: result
  until: result.status == 404
  retries: 360
  delay: 1